name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: win
            os: windows-latest

    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.platform }}
          combine: true
