name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Geode Mod
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: lukka/get-cmake@latest

      - name: Install Geode CLI
        uses: geode-sdk/install-geode-cli@main

      - name: Build Mod Manually
        run: |
          geode package --platform windows
        shell: pwsh
